###### 配置 JDBC 信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/addrook_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    ###### 设置所使用的数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    ###### 配置 Druid 连接池信息
    druid:
      min-idle: 3
      max-active: 15
      initial-size: 5
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
###### 配置 MyBatis 信息
mybatis:
  mapper-locations: classpath:/mapper/*.Mapper.xml
  type-aliases-package: cn.ekgc.bigbull.pojo.entity